datasets:
  - json_path: dataset/HPD/train_data.json
    sampling_strategy: all
    image_folder: dataset/HPD
  - json_path: dataset/LiFT-HRA/train_data.json
    sampling_strategy: all
    image_folder: dataset/LiFT-HRA
  - json_path: dataset/LLaVA-critic/pairwise/train_data.json
    sampling_strategy: all
    image_folder: dataset/LLaVA-critic/pairwise
  - json_path: dataset/LLaVA-critic/pointwise/train_data.json
    sampling_strategy: random:25000      
    image_folder: dataset/LLaVA-critic/pointwise
  - json_path: dataset/OIP/train_data.json
    sampling_strategy: random:25000
    image_folder: dataset/OIP
  - json_path: dataset/VideoFeedback/train_data.json
    sampling_strategy: all
    image_folder: dataset/VideoFeedback/frames
  - json_path: dataset/VideoDPO/train_data.json
    sampling_strategy: all
    image_folder: dataset/VideoDPO
  - json_path: dataset/EvalMuse/pairwise/train_data.json
    sampling_strategy: all
    image_folder: dataset/EvalMuse/images
  - json_path: dataset/EvalMuse/pointwise/train_data.json
    sampling_strategy: all
    image_folder: dataset/EvalMuse/images
  - json_path: dataset/ShareGPTVideo/pairwise/train_data.json
    sampling_strategy: all
    image_folder: dataset/ShareGPTVideo/videos
  - json_path: dataset/ShareGPTVideo/pointwise/train_data.json
    sampling_strategy: all
    image_folder: dataset/ShareGPTVideo/videos

